/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideScrollBar: typeof import('./src/components/AsideScrollBar.vue')['default']
    AsideScrollBarInput: typeof import('./src/components/AsideScrollBarInput.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HeaderMenu: typeof import('./src/components/HeaderMenu.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainScrollBar: typeof import('./src/components/MainScrollBar.vue')['default']
    ScrollBar: typeof import('./src/components/ScrollBar.vue')['default']
    ScrollBarInput: typeof import('./src/components/ScrollBarInput.vue')['default']
  }
}
